const LARGE_WINDOW_WIDE = 1280;
const MEDIUUM_WINDOW_WIDE = 768;
const tINY_WINDOW_WIDE = 320;

const LARGE_WINDOW_WIDE_NUMBER_RENDER = 12;
const MEDIUM_WINDOW_WIDE_NUMBER_RENDER = 8;
const TINY_WINDOW_WIDE_NUMBER_RENDER = 5;

const LARGE_WINDOW_WIDE_NUMBER_ADD = 3;
const MEDIUM_WINDOW_WIDE_NUMBER_ADD = 2;

const LOADMORE_NUMBER = 3;

export {
  LARGE_WINDOW_WIDE,
  MEDIUUM_WINDOW_WIDE,
  tINY_WINDOW_WIDE,
  LARGE_WINDOW_WIDE_NUMBER_RENDER,
  MEDIUM_WINDOW_WIDE_NUMBER_RENDER,
  TINY_WINDOW_WIDE_NUMBER_RENDER,
  LARGE_WINDOW_WIDE_NUMBER_ADD,
  MEDIUM_WINDOW_WIDE_NUMBER_ADD,
  LOADMORE_NUMBER,
};
